services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 6543:5432
    volumes:
      - ../../docker_data/postgres-docker:/var/lib/postgresql/data

  #mongo:
  #  image: mongo
  #  ports:
  #    - 27017:27017
  #  environment:
  #    - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
  #    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
  #  volumes:
  #    - ../../docker_data/mongo-docker:/data/db

  tfjupyter:
    depends_on:
      - postgres
      #- mongo
    container_name: tfjupyter
    build:
      dockerfile: ./docker/Dockerfile.tfjupyter
      context: ../
      args:
        TF_IMAGE: 2.11.0-jupyter
    #user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ../data:/tf/data
      - ../notebooks:/tf/notebooks
      - ../scripts:/tf/scripts
      - ../uselec_module:/home/uselec_module
      - ../.jupyter:/root/.jupyter
    ports:
      - 8890:8888
    #command: ["/bin/sh"]
    command: ["/usr/local/bin/jupyter",
      "notebook",
      "--ip", "0.0.0.0",
      "--port", "8888",
      "--no-browser",
      "--allow-root",
      "--NotebookApp.allow_origin_pat=https://.*vscode-cdn\\.net",
      "--notebook-dir", "/tf"]
