services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PG_ROOT_PASSWORD}
      POSTGRES_USER: ${PG_ROOT_USER}
      POSTGRES_DB: ${PG_DEV_DB}
    ports:
      - 6543:5432
    volumes:
      - ../../docker_data/postgres-docker:/var/lib/postgresql/data
      - ./files/sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  tfjupyter-gpu:
    depends_on:
      - postgres
      #- mongo
    container_name: tfjupyter-gpu
    build:
      dockerfile: ./docker/Dockerfile.tfjupyter
      context: ../
      args:
        TF_IMAGE: 2.11.0-gpu-jupyter
    #user: ${DOCKER_UID:-1000}:${DOCKER_GID:-1000}
    environment:
      PG_DEV_PASSWORD: ${PG_DEV_PASSWORD}
      PG_DEV_USER: ${PG_DEV_USER}
      PG_DEV_DB: ${PG_DEV_DB}
      PG_TEST_PASSWORD: ${PG_TEST_PASSWORD}
      PG_TEST_USER: ${PG_TEST_USER}
      PG_TEST_DB: ${PG_TEST_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ../data:/tf/data
      - ../notebooks:/tf/notebooks
      - ../scripts:/tf/scripts
      - ../code:/home/code
      - ../.jupyter:/root/.jupyter
      - ../.history:/home/.history
      - ~/.aws:/root/.aws
    ports:
      - 8890:8888
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    #command: ["/bin/sh"]
    command: ["/usr/local/bin/jupyter",
      "notebook",
      "--ip", "0.0.0.0",
      "--port", "8888",
      "--no-browser",
      "--allow-root",
      "--NotebookApp.allow_origin_pat=https://.*vscode-cdn\\.net",
      "--notebook-dir", "/tf"]

  #mongo:
  #  image: mongo
  #  ports:
  #    - 27017:27017
  #  environment:
  #    - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
  #    - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
  #  volumes:
  #    - ../../docker_data/mongo-docker:/data/db