# List of 3 biggest cities in each state.
names = ["State", "L1", "L2", "L3"]
city_list = [
    ["AL", "Birmingham", "Mobile", "Huntsville"],
    ["AK", "Anchorage", "Fairbanks", "Juneau"],
    ["AZ", "Phoenix", "Tucson", "Mesa"],
    ["AR", "Little Rock", "Fort Smith", "Fayetteville"],
    ["CA", "Los Angeles", "San Diego", "San Jose"],
    ["CO", "Denver", "Colorado Springs", "Aurora"],
    ["CN", "Bridgeport", "New Haven", "Hartford"],
    ["DE", "Wilmington", "Dover", "Newark"],
    ["FL", "Jacksonville", "Miami", "Tampa"],
    ["GA", "Atlanta", "Augusta", "Columbus"],
    ["HI", "Honolulu", "Hilo", "Kailua"],
    ["ID", "Boise", "Nampa", "Idaho Falls"],
    ["IL", "Chicago", "Aurora", "Rockford"],
    ["IN", "Indianapolis", "Fort Wayne", "Evansville"],
    ["IA", "Des Moines", "Cedar Rapids", "Davenport"],
    ["KA", "Wichita", "Overland Park", "Kansas City"],
    ["KY", "Louisville", "Lexington", "Owensboro"],
    ["LA", "New Orleans", "Shreveport", "Baton Rouge"],
    ["ME", "Portland", "Lewiston", "Bangor"],
    ["MD", "Baltimore", "Frederick", "Gaithersburg"],
    ["MA", "Boston", "Worcester", "Springfield"],
    ["MI", "Detroit", "Grand Rapids", "Warren"],
    ["MN", "Minneapolis", "Saint Paul", "Rochester"],
    ["MS", "Jackson", "Gulfport", "Biloxi"],
    ["MO", "Kansas City", "Saint Louis", "Springfield"],
    ["MT", "Billings", "Missoula", "Great Falls"],
    ["NE", "Omaha", "Lincoln", "Bellevue"],
    ["NV", "Las Vegas", "Reno", "Henderson"],
    ["NH", "Manchester", "Nashua", "Concord"],
    ["NJ", "Newark", "Jersey City", "Paterson"],
    ["NM", "Albuquerque", "Las Cruces", "Rio Rancho"],
    ["NY", "New York City", "Buffalo", "Rochester"],
    ["NC", "Charlotte", "Raleigh", "Greensboro"],
    ["ND", "Fargo", "Bismarck", "Grand Forks"],
    ["OH", "Columbus", "Cleveland", "Cincinnati"],
    ["OK", "Oklahoma City", "Tulsa", "Norman"],
    ["OR", "Portland", "Salem", "Eugene"],
    ["PA", "Philadelphia", "Pittsburgh", "Allentown"],
    ["RI", "Providence", "Warwick", "Cranston"],
    ["SC", "Charleston", "Columbia", "North Charleston"],
    ["SD", "Sioux Falls", "Rapid City", "Aberdeen"],
    ["TN", "Memphis", "Nashville", "Knoxville"],
    ["TX", "Houston", "San Antonio", "Dallas"],
    ["UT", "Salt Lake City", "West Valley City", "Provo"],
    ["VT", "Burlington", "South Burlington", "Rutland"],
    ["VI", "Virginia Beach", "Norfolk", "Chesapeake"],
    ["WA", "Seattle", "Spokane", "Tacoma"],
    ["WV", "Charleston", "Huntington", "Parkersburg"],
    ["WI", "Milwaukee", "Madison", "Green Bay"],
    ["WY", "Cheyenne", "Casper", "Laramie"],
]


# Make list of states
states = (
    "Alabama",
    "Alaska",
    "Arizona",
    "Arkansas",
    "California",
    "Colorado",
    "Connecticut",
    "Delaware",
    "Florida",
    "Georgia",
    "Hawaii",
    "Idaho",
    "Illinois",
    "Indiana",
    "Iowa",
    "Kansas",
    "Kentucky",
    "Louisiana",
    "Maine",
    "Maryland",
    "Massachusetts",
    "Michigan",
    "Minnesota",
    "Mississippi",
    "Missouri",
    "Montana",
    "Nebraska",
    "Nevada",
    "New Hampshire",
    "New Jersey",
    "New Mexico",
    "New York",
    "North Carolina",
    "North Dakota",
    "Ohio",
    "Oklahoma",
    "Oregon",
    "Pennsylvania",
    "Rhode Island",
    "South Carolina",
    "South Dakota",
    "Tennessee",
    "Texas",
    "Utah",
    "Vermont",
    "Virginia",
    "Washington",
    "West Virginia",
    "Wisconsin",
    "Wyoming",
)
